### ISSUE TITLE
Support anyOf, oneOf and allOf

### ISSUE THREAD

**Issue by mohsen1** [mohsen1/json-schema-view#1]

**Comment by fishermand46** [comment]
This seems like it would be really difficult considering all the possible ways schemas can be combined. Do you think this is even possible?

**Comment by mohsen1** [comment]
I was thinking of adding a level of hierarchy for these. for example if the schema is like this:

``` yaml
    Person:
      type: object
      properties:
        education:
          oneOf: 
            - type: object
              properties:
                school:
                  type: string
                year:
                  type: integer
            - type: string
```

Then we should render it like following:

```
  > Person 
    > education oneOf
      > {}
      > string
```

We should render the label `oneOf` in a different color so it's very obvious to user
